// Generated by CoffeeScript 1.10.0
(function() {
  window.__nspeed = function(callback) {
    var image, image_size, image_url, start_time;
    image_url = 'https://upload.wikimedia.org/wikipedia/commons/d/d9/Big_Bear_Valley,_California.jpg';
    image_size = 3422075 * 8;
    image = new Image;
    image.onload = function() {
      var finish_time, speed, time_result, time_result_in_sec;
      finish_time = (new Date()).getTime();
      time_result = finish_time - start_time;
      time_result_in_sec = time_result / 1000;
      speed = ((image_size / time_result_in_sec) / (1024 * 1024)).toFixed(2);
      return callback(speed);
    };
    start_time = (new Date()).getTime();
    return image.src = image_url + ("?" + start_time);
  };

}).call(this);
